CREATE DATABASE QLBANSACH

GO

USE QLBANSACH

GO

CREATE TABLE TACGIA
(
	MaTG INT IDENTITY PRIMARY KEY,
	TenTG NVARCHAR(100),
	DiaChi NVARCHAR(255),
	TieuSu TEXT,
	DienThoai VARCHAR(15)
)

CREATE TABLE CHUDE
(
	MaCD INT IDENTITY PRIMARY KEY,
	TenChuDe NVARCHAR(100)
)

CREATE TABLE NHAXUATBAN
(
	MaNXB INT IDENTITY PRIMARY KEY,
	TenNXB NVARCHAR(100),
	DiaChi NVARCHAR(255),
	DienThoai VARCHAR(15)
)

CREATE TABLE KHACHHANG
(
	MaKH INT IDENTITY PRIMARY KEY,
	HoTen NVARCHAR(100),
	TaiKhoan VARCHAR(50),
	MatKhau VARCHAR(50),
	Email VARCHAR(100),
	DiaChiKH NVARCHAR(255),
	DienThoaiKH VARCHAR(15),
	NgaySinh DATE
)

CREATE TABLE SACH
(
	MaSach INT IDENTITY PRIMARY KEY,
	TenSach NVARCHAR(100),
	GiaBan MONEY,
	MoTa TEXT,
	AnhBia NVARCHAR(255),
	NgayCapNhat DATETIME,
	SoLuongTon INT,
	MaCD INT,
	MaNXB INT,
	FOREIGN KEY (MaCD) REFERENCES ChuDe(MaCD) ON UPDATE CASCADE,
	FOREIGN KEY (MaNXB) REFERENCES NhaXuatBan(MaNXB) ON UPDATE CASCADE
)

CREATE TABLE VIETSACH
(
	MaTG INT,
	MaSach INT,
	VaiTro INT,
	ViTri NVARCHAR(100),
	PRIMARY KEY (MaTG, MaSach),
	FOREIGN KEY (MaTG) REFERENCES TacGia(MaTG) ON UPDATE CASCADE,
	FOREIGN KEY (MaSach) REFERENCES Sach(MaSach) ON UPDATE CASCADE
)

CREATE TABLE DONDATHANG
(
	MaDonHang INT IDENTITY PRIMARY KEY,
	DaThanhToan BIT,
	TinhTrangGiaoHang BIT,
	NgayDat DATETIME,
	NgayGiao DATETIME,
	MaKH INT,
	FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH) ON UPDATE CASCADE,
)

CREATE TABLE CHITIETDONHANG
(
	MaDonHang INT,
	MaSach INT,
	SoLuong INT,
	DonGia Money,
	PRIMARY KEY(MaDonHang, MaSach),
	FOREIGN KEY (MaDonHang) REFERENCES DONDATHANG(MaDonHang) ON UPDATE CASCADE,
	FOREIGN KEY (MaSach) REFERENCES SACH(MaSach) ON UPDATE CASCADE,
)